// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package codeu.model.data;

import java.time.Instant;
import java.util.UUID;

/** Class representing a registered user. */
public class User {
  private final UUID id;
  private final String name;
  private final String passwordHash;
  private final Instant creation;
  private boolean admin;
  private String aboutMe;

  /**
   * Constructs a new User.
   *
   * @param id the ID of this User
   * @param name the username of this User
   * @param passwordHash the password hash of this User
   * @param creation the creation time of this User
   */
  public User(UUID id, String name, String passwordHash, Instant creation) {
    this.id = id;
    this.name = name;
    this.passwordHash = passwordHash;
    this.creation = creation;
    this.admin = false;
    this.aboutMe = "";
  }

  /** Returns the ID of this User. */
  public UUID getId() {
    return id;
  }

  /** Returns the username of this User. */
  public String getName() {
    return name;
  }

  /** Returns the password hash of this User. */
  public String getPasswordHash() {
    return passwordHash;
  }

  /** Returns the creation time of this User. */
  public Instant getCreationTime() {
    return creation;
  }

  /** Returns the Admin status of the user. */
  public boolean isAdmin() {
    return admin;
  }

  /** Sets the admin status of the user. */
  public void setAdmin(boolean status) {
    this.admin = status;
  }

  /** Returns the about me section of this User. */
  public String getAboutMe() {
    return aboutMe;
  }

  /** Sets the about me String of this User. */
  public void setAboutMe(String aboutMe) {
    this.aboutMe = aboutMe;
  }

  /** Auto-generated by Eclipse. Must be updated if any fields are added to this class. */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((aboutMe == null) ? 0 : aboutMe.hashCode());
    result = prime * result + (admin ? 1231 : 1237);
    result = prime * result + ((creation == null) ? 0 : creation.hashCode());
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    result = prime * result + ((name == null) ? 0 : name.hashCode());
    result = prime * result + ((passwordHash == null) ? 0 : passwordHash.hashCode());
    return result;
  }

  /** Auto-generated by Eclipse. Must be updated if any fields are added to this class. */
  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    User other = (User) obj;
    if (aboutMe == null) {
      if (other.aboutMe != null) return false;
    } else if (!aboutMe.equals(other.aboutMe)) return false;
    if (admin != other.admin) return false;
    if (creation == null) {
      if (other.creation != null) return false;
    } else if (!creation.equals(other.creation)) return false;
    if (id == null) {
      if (other.id != null) return false;
    } else if (!id.equals(other.id)) return false;
    if (name == null) {
      if (other.name != null) return false;
    } else if (!name.equals(other.name)) return false;
    if (passwordHash == null) {
      if (other.passwordHash != null) return false;
    } else if (!passwordHash.equals(other.passwordHash)) return false;
    return true;
  }
}
